baseURL = "https://sainthillier.fr"
languageCode = "fr-FR"
title = "Guillaume Sainthillier"
googleAnalytics = "G-DBS1G509Q7"
assetDir = "static"


disableKinds = ["taxonomy", "RSS"]

[imaging]
  resampleFilter = "Linear"

[params]
  description = "Développeur web freelance à Toulouse. Développeur freelance PHP. Contactez rapidement un développeur web à Toulouse pour réaliser votre projet Web."

[params.social]
  github = "https://github.com/guillaume-sainthillier"
  linkedin = "https://www.linkedin.com/in/developpeur-web-toulouse/"
